# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Copy dependencies definitions
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN pip install --no-cache-dir pip && \
    pip install --no-cache-dir .

# Copy the rest of the application
COPY . .

# Default command to run the MCP server
CMD ["python", "main.py"]
